<?php

declare(strict_types=1);

require_once __DIR__ . '/../src/bootstrap.php';

use App\Controllers\EmbeddedController;
use App\Controllers\HomeController;
use App\Controllers\OAuthController;
use App\Controllers\ProductController;
use App\Controllers\WebhookController;
use App\Controllers\AuthController;
use App\Controllers\AdminController;
use App\Controllers\PageController;
use App\Router;

$router = new Router();

$router->get('/', [HomeController::class, 'index']);
$router->get('/about', [PageController::class, 'about']);
$router->get('/faq', [PageController::class, 'faq']);
$router->get('/pricing', [PageController::class, 'pricing']);
$router->get('/privacy', [PageController::class, 'privacy']);
$router->get('/terms', [PageController::class, 'terms']);
$router->get('/admin/login', [AdminController::class, 'loginForm']);
$router->post('/admin/login', [AdminController::class, 'loginSubmit']);
$router->get('/admin/logout', [AdminController::class, 'logout']);
$router->get('/admin/dashboard', [AdminController::class, 'dashboard']);
$router->get('/admin/stores', [AdminController::class, 'stores']);
$router->get('/admin/stores/{id}', [AdminController::class, 'store']);
$router->post('/admin/stores/{id}/subscription', [AdminController::class, 'updateSubscription']);
$router->post('/admin/stores/{id}/adjust-quotas', [AdminController::class, 'adjustQuotas']);
$router->post('/admin/stores/{id}/delete', [AdminController::class, 'deleteStore']);
$router->get('/admin/activity', [AdminController::class, 'activity']);
$router->post('/admin/email-test', [AdminController::class, 'sendTestEmail']);
$router->get('/login', [AuthController::class, 'loginForm']);
$router->post('/login', [AuthController::class, 'loginSubmit']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/api/auth/reconnect', [AuthController::class, 'reconnect']);
$router->get('/forgot-password', [AuthController::class, 'forgotPasswordForm']);
$router->post('/forgot-password', [AuthController::class, 'forgotPasswordSubmit']);
$router->get('/set-password', [AuthController::class, 'setPasswordForm']);
$router->post('/set-password', [AuthController::class, 'setPasswordSubmit']);
$router->get('/dashboard', [AuthController::class, 'dashboard']);
$router->get('/oauth/callback', [OAuthController::class, 'callback']);
$router->post('/webhooks/salla', [WebhookController::class, 'handle']);
$router->get('/embedded', [EmbeddedController::class, 'index']);
$router->get('/api/products', [ProductController::class, 'index']);
$router->get('/api/brands', [ProductController::class, 'brands']);
$router->get('/api/categories', [ProductController::class, 'categories']);
$router->get('/api/subscription', [ProductController::class, 'subscription']);
$router->get('/api/settings', [ProductController::class, 'optimizationSettings']);
$router->post('/api/settings/save', [ProductController::class, 'saveOptimizationSettings']);
$router->post('/api/sitemap/save', [ProductController::class, 'saveSitemapSettings']);
$router->get('/api/operations', [ProductController::class, 'operations']);
$router->post('/api/keywords/research', [ProductController::class, 'keywordResearch']);
$router->get('/api/keywords/history', [ProductController::class, 'keywordHistory']);
$router->get('/api/domain-seo', [ProductController::class, 'domainSeo']);
$router->post('/api/domain-seo/save', [ProductController::class, 'saveDomainSeo']);
$router->post('/api/domain-seo/refresh', [ProductController::class, 'refreshDomainSeo']);
$router->get('/api/domain-seo/history', [ProductController::class, 'domainSeoHistory']);
$router->get('/api/store-seo', [ProductController::class, 'storeSeo']);
$router->post('/api/store-seo/optimize', [ProductController::class, 'optimizeStoreSeo']);
$router->post('/api/store-seo/instructions/save', [ProductController::class, 'saveStoreSeoInstructions']);
$router->post('/api/store-seo/save', [ProductController::class, 'saveStoreSeo']);
$router->post('/api/brands/{id}/optimize', [ProductController::class, 'optimizeBrandSeo']);
$router->post('/api/brands/{id}/save', [ProductController::class, 'saveBrandSeo']);
$router->post('/api/categories/{id}/optimize', [ProductController::class, 'optimizeCategorySeo']);
$router->post('/api/categories/{id}/save', [ProductController::class, 'saveCategorySeo']);
$router->post('/api/products/alt/bulk', [ProductController::class, 'bulkOptimizeVisibleImagesAlt']);
$router->post('/api/products/{id}/optimize', [ProductController::class, 'optimize']);
$router->post('/api/products/{id}/save-description', [ProductController::class, 'saveDescription']);
$router->get('/api/products/{id}/edit-manual', [ProductController::class, 'getProductForManualEdit']);
$router->post('/api/products/{id}/save-manual', [ProductController::class, 'saveProductManual']);
$router->post('/api/products/{id}/images/optimize-alt', [ProductController::class, 'optimizeProductImagesAlt']);
$router->post('/api/products/{id}/images/save-alt', [ProductController::class, 'saveProductImagesAlt']);
$router->post('/api/products/{id}/images/{imageId}/optimize-alt', [ProductController::class, 'optimizeImageAlt']);
$router->post('/api/products/{id}/images/{imageId}/save-alt', [ProductController::class, 'saveImageAlt']);

$router->dispatch($_SERVER['REQUEST_METHOD'] ?? 'GET', $_SERVER['REQUEST_URI'] ?? '/');
